version: '3'
services:
  app:
    container_name: flask_app
    build:
      context: .
      dockerfile: Dockerfile
    links:
      - mysql
    ports:
      - "5000:5000"
  mysql:
    container_name: flask_mysql
    image: mysql:5.7    
    ports:
      - "32000:3306"
    environment:
        # set database, memcached etc credentials
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ./db:/docker-entrypoint-initdb.d/:ro